image: Visual Studio 2019

version: 4.0.{build}

branches:
  only:
    - master

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
configuration: Debug

install:
  - cmd: choco install dotnetcore-sdk --pre
  
before_build:
  - externalDlls\libnodave\vcwinmake_64.bat
  - externalDlls\libnodave\vcwinmake.bat
  - externalDlls\copydlls.bat
  - nuget restore
  
build:
  project: DotNetSiemensPLCToolBoxLibrary.sln

artifacts:
  - path: externalDlls\libnodave\libnodave_jfkmod.dll
    name: libnodave_jfkmod.dll
  - path: externalDlls\libnodave\libnodave_jfkmod64.dll
    name: libnodave_jfkmod64.dll
  - path: '**\DotNetSiemensPLCToolBoxLibrary*.nupkg' 

deploy:
  provider: NuGet
  api_key:
    secure: OrhpK2cLXXcoWW+hU6xAv3eeKIbATEFbenteoFsi9EfM1yyDof6ZuNKAsA3Vy6vb
  artifact: /.*\.nupkg/
  
  
  
