image: Visual Studio 2019

version: 4.0.{build}

branches:
  only:
    - master

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
configuration: Debug

before_build:
  - nuget restore
  
build:
  project: DotNetSiemensPLCToolBoxLibrary.sln

after_build:
  - externalDlls\libnodave\vcwinmake.bat
  - externalDlls\libnodave\vcwinmake_64.bat
  - ps: .\nuget\pack.ps1
  - 7z a TiaGitHandler.zip %APPVEYOR_BUILD_FOLDER%\compiled\DotNetSiemensPLCToolBoxLibrary.dll %APPVEYOR_BUILD_FOLDER%\compiled\DotNetSiemensPLCToolBoxLibrary.TIAV13.dll %APPVEYOR_BUILD_FOLDER%\compiled\DotNetSiemensPLCToolBoxLibrary.TIAV14SP1.dll %APPVEYOR_BUILD_FOLDER%\compiled\DotNetSiemensPLCToolBoxLibrary.TIAV15.dll %APPVEYOR_BUILD_FOLDER%\compiled\DotNetSiemensPLCToolBoxLibrary.TIAV15_1.dll %APPVEYOR_BUILD_FOLDER%\compiled\ICSharpCode.SharpZipLib.dll %APPVEYOR_BUILD_FOLDER%\compiled\TiaGitHandler.exe
  - 7z a S7ToolBox.zip %APPVEYOR_BUILD_FOLDER%\compiled\AvalonDock.dll %APPVEYOR_BUILD_FOLDER%\compiled\AvalonDock.Themes.dll %APPVEYOR_BUILD_FOLDER%\compiled\DotNetSiemensPLCToolBoxLibrary.dll %APPVEYOR_BUILD_FOLDER%\compiled\DotNetSiemensPLCToolBoxLibrary.TIAV13.dll %APPVEYOR_BUILD_FOLDER%\compiled\DotNetSiemensPLCToolBoxLibrary.TIAV14SP1.dll %APPVEYOR_BUILD_FOLDER%\compiled\DotNetSiemensPLCToolBoxLibrary.TIAV15.dll %APPVEYOR_BUILD_FOLDER%\compiled\DotNetSiemensPLCToolBoxLibrary.TIAV15_1.dll %APPVEYOR_BUILD_FOLDER%\compiled\ICSharpCode.AvalonEdit.dll %APPVEYOR_BUILD_FOLDER%\compiled\ICSharpCode.SharpZipLib.dll %APPVEYOR_BUILD_FOLDER%\externalDlls\Interop.HMIGENOBJECTSLib.dll %APPVEYOR_BUILD_FOLDER%\compiled\JFKCommonLibrary.dll %APPVEYOR_BUILD_FOLDER%\externalDlls\libnodave_jfkmod.dll %APPVEYOR_BUILD_FOLDER%\externalDlls\libnodave_jfkmod64.dll %APPVEYOR_BUILD_FOLDER%\compiled\System.Windows.Interactivity.dll %APPVEYOR_BUILD_FOLDER%\compiled\ToolboxForSiemensPLCs.exe %APPVEYOR_BUILD_FOLDER%\compiled\WPFToolboxForSiemensPLCs.exe
  - 7z a WPFVarTab.zip %APPVEYOR_BUILD_FOLDER%\compiled\CustomChromeLibrary.dll %APPVEYOR_BUILD_FOLDER%\compiled\DotNetSiemensPLCToolBoxLibrary.dll %APPVEYOR_BUILD_FOLDER%\compiled\DotNetSiemensPLCToolBoxLibrary.TIAV13.dll %APPVEYOR_BUILD_FOLDER%\compiled\DotNetSiemensPLCToolBoxLibrary.TIAV14SP1.dll %APPVEYOR_BUILD_FOLDER%\compiled\DotNetSiemensPLCToolBoxLibrary.TIAV15.dll %APPVEYOR_BUILD_FOLDER%\compiled\DotNetSiemensPLCToolBoxLibrary.TIAV15_1.dll %APPVEYOR_BUILD_FOLDER%\compiled\ICSharpCode.SharpZipLib.dll %APPVEYOR_BUILD_FOLDER%\externalDlls\JFKCommonLibrary.dll %APPVEYOR_BUILD_FOLDER%\externalDlls\libnodave_jfkmod.dll %APPVEYOR_BUILD_FOLDER%\externalDlls\libnodave_jfkmod64.dll %APPVEYOR_BUILD_FOLDER%\compiled\System.Windows.Interactivity.dll %APPVEYOR_BUILD_FOLDER%\compiled\WPFToolkit.Extended.dll %APPVEYOR_BUILD_FOLDER%\compiled\WPFVarTab.exe %APPVEYOR_BUILD_FOLDER%\compiled\Microsoft.Windows.Shell.dll
  
artifacts:
  - path: externalDlls\libnodave\libnodave_jfkmod.dll
    name: libnodave_jfkmod.dll
  - path: externalDlls\libnodave\libnodave_jfkmod64.dll
    name: libnodave_jfkmod64.dll
  - path: '**\DotNetSiemensPLCToolBoxLibrary*.nupkg' 
#uncomment to publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: OrhpK2cLXXcoWW+hU6xAv3eeKIbATEFbenteoFsi9EfM1yyDof6ZuNKAsA3Vy6vb
  artifact: /.*\.nupkg/
  
  
  
